# permissions for end users to view schedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduler-viewer-role
rules:
- apiGroups:
  - gcp-contrib.alleypinapis.com
  resources:
  - schedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp-contrib.alleypinapis.com
  resources:
  - schedulers/status
  verbs:
  - get
